version: '3'
services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex
      - POSTGRES_DB=myClevertecDB
      - config.support_escapes=true
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - odfe-net
  liquibase:
    build: ./liquibase
    depends_on:
      - db
    volumes:
      - ./changelog:/liquibase
    environment:
      LIQUIBASE_URL: jdbc:postgresql://db:5432/myClevertecDB
      LIQUIBASE_USERNAME: alex
      LIQUIBASE_PASSWORD: alex
      LIQUIBASE_CHANGELOG_FILE: changelog.xml
    networks:
      - odfe-net
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: odfe-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms700m -Xmx700m"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - odfe-net
  kibana:
    image: kibana:7.10.1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    container_name: odfe-kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://odfe-node:9200
      ELASTICSEARCH_HOSTS: http://odfe-node:9200
    networks:
      - odfe-net
  logstash:
    user: root
    image: docker.elastic.co/logstash/logstash-oss:7.9.1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ports:
      - "5044:5044"
    depends_on:
      - db
      - elasticsearch
    environment:
      - PIPELINE_WORKERS=1
      - PIPELINE_BATCH_SIZE=125
      - PIPELINE_BATCH_DELAY=50
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash_data:/usr/share/logstash/data
      - ./conf/postgresql-42.6.0.jar:/usr/share/logstash/postgresql-42.6.0.jar
    networks:
      - odfe-net
networks:
  odfe-net:
    driver: bridge